### ISSUE TITLE
HDR support?

### ISSUE THREAD

**Issue by alexlyee** [gnif/LookingGlass#1045]
I'm unsure if this has been explored before, and I'm relatively new to all of this, so I apologize for my ignorance beforehand. I'd like to pass through HDR content from Windows to my Linux host. I'm aware that this is complicated and perhaps impossible on many distros right now, but I also heard that it could be possible to "trick" Linux intro displaying the content in HDR. Perhaps, in fullscreen, my monitor would then recognize the incoming HDR signal and display it as such?

**Comment by netboy3** [comment]
LG doesn't do anything special to handle HDR, it just knows the format has changed and asks the GPU to render it, and because none of the Linux display servers currently support HDR, trying it is pretty pointless. You just end up wasting double the memory and bandwidth with no benefits. There's some early work being done on this with AMD Xorg, but it's a long way from completion. You can Google the subject to learn more of the status.

**Comment by alexlyee** [comment]
@netboy3 thank you for this! I have been searching it up lately and am learning a lot, I thought I'd ask here though in case there was any breaking progress on the subject that I haven't already heard. I really hope HDR on linux becomes a reality sooner than later, because it's fantastic with the modern backlight-less display panels that will in a future not too far from now will become the new normal (if they aren't already..)

also I wonder if it helps with color accuracy and graphic design, though I don't feel qualified to say with certainty it always does

**Comment by gnif** [comment]
Closing as not an issue, if you wish to discuss the future of the project, or the project in general please join the community at https://looking-glass.io/discord
