### ISSUE TITLE
Is there any solution to the trouble caused by ivshmem?

### ISSUE THREAD

**Issue by daiaji** [gnif/LookingGlass#1083]
https://github.com/virtio-win/kvm-guest-drivers-windows/issues/911
https://gitlab.com/virtio-fs/virtiofsd/-/issues/96
https://gitlab.com/virtio-fs/virtiofsd/-/issues/92#note_1446075260
https://www.reddit.com/r/NixOS/comments/149pvwd/virtiofsd_stopped_working/
```xml
  <qemu:commandline>
    <qemu:arg value='-device'/>
    <qemu:arg value='{&quot;driver&quot;:&quot;ivshmem-plain&quot;,&quot;id&quot;:&quot;shmem0&quot;,&quot;memdev&quot;:&quot;looking-glass&quot;}'/>
    <qemu:arg value='-object'/>
    <qemu:arg value='{&quot;qom-type&quot;:&quot;memory-backend-file&quot;,&quot;id&quot;:&quot;looking-glass&quot;,&quot;mem-path&quot;:&quot;/dev/kvmfr0&quot;,&quot;size&quot;:33554432,&quot;share&quot;:true}'/>
  </qemu:commandline>
Other than that, there seems
``` 
Follow [German Maglione's advice](https://github.com/virtio-win/kvm-guest-drivers-windows/issues/911#issuecomment-1607912984) and ask for help.
Looks like the failure is caused by creating ivshmem.
to be no other progress.

**Comment by gnif** [comment]
The IVSHMEM virtual device is not a Looking Glass device, if it's causing a conflict with virtiofs then open an issue with QEMU.

**Comment by hasechris** [comment]
I opened a Issue entry at qemu's gitlab. Tracking here for google-users.
https://gitlab.com/qemu-project/qemu/-/issues/1877

**Comment by gnif** [comment]
Thanks for opening the issue with the appropriate project, hopefully the maintainer of the code that is failing is able to correct this. This is the correct way to go about getting this fixed.

I do not however appreciate your rudeness towards me for giving the exact details needed to obtain support for this issue. The crash is in QEMU, there is absolutely zero way anything you do in a guest VM should ever be able to crash QEMU for any reason. I have no idea as to what the cause is, or where to even look to debug this as it's not my code or code I am familiar with.
