### ISSUE TITLE
Issue 1083 closed prematurly?

### ISSUE THREAD

**Issue by hasechris** [gnif/LookingGlass#1089]
Issue regarding the issue 
https://github.com/gnif/LookingGlass/issues/1083

You said
> The IVSHMEM virtual device is not a Looking Glass device, 

Sadly the config, as stated from the user, is exactly the qemu config from your documentation:
https://looking-glass.io/docs/B6/module/#libvirt

Could you please reopen the issue 1083?

Thanks
hasechris

**Comment by hasechris** [comment]
I'm really sorry, but your mindset is really NOT HELPING.

Normal users are using YOUR Config example (which is needed for looking-glass), which breaks some other software, and you are NOT willing to just look into this only 5 minutes.

What a crap!

**Comment by gnif** [comment]
:facepalm: 

1. The config provided is fully working and used by thousands without issue.
2. IVSHMEM is part of QEMU and LG simply makes use of it. The config provided is an example of how to add this to your VM, if you are using other QEMU features that cause a conflict, then you need to talk to the QEMU developers and report the issue to them.
3. Our config and/or software does not break other software, QEMU clearly has a bug as our config can only be done one way, is valid, correct, and validated by the QEMU documentation.

And finally, **This is FREE software**, you did not pay for it, nor did you pay me for my time to look at your issue or respond to you with a valid and correct answer. Your assumption that I have not spent more then 5 minutes on this issue is demonstrably false.

Your feeling that you are entitled to my time, a portion of my life, when I have already spent well over a thousand hours on this project, for FREE, is the wrong mind set. What crap indeed.
