### ISSUE TITLE
It crashes when selecting an element on PopOs

### ISSUE THREAD

**Issue by lko3001** [gnif/LookingGlass#1107]
Most of the times, when i open looking glass, I select an element, and then it crashes, I am not able t
- type anymore into the Looking Glass' input bar
- use shortcuts (for example to switch workspace or quit stuff)
- close looking glass by pressing esc
The only solution I found is to refresh the gnome-shell, either from the terminal or by pressing `alt+f2` and then typing `r`.
Sometimes, it gets stuck on top of the screen and even if I select it and press `Esc` it doesn't close

That's the bug that I've found, I only started using Linux a few months ago so if I might have missed some important information

OS: Pop!_OS 22.04 LTS x86_64 
Host: Legion 5 Pro 16ACH6H 
Kernel: 6.6.10-76060610-generic 
Packages: 2253 (dpkg), 4 (snap) 
Shell: bash 5.1.16 
Resolution: 3408x2130 
DE: GNOME 42.5 
WM: Mutter 
WM Theme: Pop 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 5800H with Radeon Gr 
GPU: NVIDIA GeForce RTX 3060 Mobile
Memory: 3725MiB / 15844MiB

**Comment by netboy3** [comment]
Please note that opening an issue on this Github repo is reserved for verified bugs and feature suggestions. We have users on PopOS and many users on Ubuntu and no one has reported such grave problems. Your issue is almost certainly because of build/setup/configuration. Please use either the [LG Forum](https://forum.level1techs.com/c/software/lookingglass/142), or the support channel on the [LG Discord](https://looking-glass.io/discord) to request assistance. Make sure to post full logs (both client and host-app) and your VM XML.
