### ISSUE TITLE
The a12 version still can't let me use AMD graphics on the host?

### ISSUE THREAD

**Issue by daiaji** [gnif/LookingGlass#119]
I expect to replace the GTX1050TI on Host with AMD's new graphics card in the future.

**Comment by gnif** [comment]
AMD host graphics work fine. This issue is to be closed as you did not follow the explicit and obvious instructions when opening an issue.

### Required information

Host CPU:
Host GPU:
Guest GPU:
Host Kernel version:
Host QEMU version:

Please describe what were you doing when the problem occured. If the Windows host application crashed please check for file named `looking-glass-host.dmp` and attach it to this bug report.

**Reports that do no include this information will be ignored and closed**
