### ISSUE TITLE
Windows IVSHMEM driver not present in system

### ISSUE THREAD

**Issue by tsalwierz** [gnif/LookingGlass#169]
Host CPU: i7-8700k
Host GPU: passthrough
Guest 1 GPU: UHD 630
Guest 1 has the VM to VM module installed.
Guest 2 GPU: 2080 ti
Host Kernel version: 4.15.18-15-pve
Host QEMU version: 1:2.8+dfsg-6+deb9u7

I have Windows 10 home installed on Guest 2 and cannot install the IVSHMEM driver as the "PCI standard RAM Controller" is absent.

There is a device that is "not working" and I can install the driver to it, but it continues to say it's not working/broken, so I don't think that's the RAM Controller. It also requires a driver reinstall every reboot.

Is Windows 10 pro a requirement for this to work? Or is this a limitation with my cpu settings/chipset in qemu?

The only thing I can think of is spice is disabled (drivers are installed though). But spice isn't supposed to be a requirement for Looking Glass, so doubt that's it.

![image-2](https://user-images.githubusercontent.com/7935624/59139560-90b5e080-8948-11e9-9a3d-93f8cdd584a8.jpg)

![image-1](https://user-images.githubusercontent.com/7935624/59139562-96132b00-8948-11e9-85d8-a37d06650ef1.jpg)

![mmc_cPcdP9xe8N](https://user-images.githubusercontent.com/7935624/59139596-ea1e0f80-8948-11e9-9df5-ae65fd825d64.png)

**Comment by tsalwierz** [comment]
It turns out both KVM need to have the ivshmem arguments, which isn't mentioned anywhere.

**Comment by gnif** [comment]
This is not mentioned anywhere as this is a QEMU issue and not a Looking Glass issue. These issues are for Looking Glass problems only!

**Comment by fspkwon** [comment]
MDEV device isnt registered i see people are using a consoleified linux im trying just on gentoo and am having RAMFB issues
where TIANOCORE when handing off to Windows Recovery EFI thats FINE but i and have also theres 2 MDEV devices one 32mb one 64mb and the guide says it counts down which one you use .... and just the text and logo stay resident where the scroller
just goes away . IVSHMEM im using Windows 10 and Looking-Glass 5..... it cant connect to spice... whether or gives permission denied i do not know why thats for but only occurs in the newer one i think.. but IVSHMEM keeps uninstalling itself<- so what im doing now is using RDP to perform a CLEAN Intel Driver Installation... but the where PCI Ram Controller isnt showing up thats because you didnt create the IVSHMEM Shared Diplay in Linux meaning the part of the Guide that says create the dummy display and in virt-manager or whatever your using itll show up as a Device in MDEV selection then has to Turn Display on and RamFB on using the XML editor if im correct

**Comment by fspkwon** [comment]
ok and the creating Shared DIsplay has to be done on Reboot or configure it as an init.d Service
