### ISSUE TITLE
Client sometimes starts jittering

### ISSUE THREAD

**Issue by JJRcop** [gnif/LookingGlass#185]
### Required information

Host CPU: Ryzen 5 2600
Host GPU: Radeon RX 580
Guest GPU: GeForce GTX 970
Host Kernel version: 4.19.0-5-amd64 #1 SMP Debian 4.19.37-6 (2019-07-18)
Host QEMU version: QEMU emulator version 3.1.0 (Debian 1:3.1+dfsg-8)

----

Sometimes the client will start jittering on the current release (163a2e5) after a random amount of time of working perfectly.

I've already reported it on [the triage thread], but I'm having trouble reliably reproducing it to find the cause. I've created this issue to see if others have noticed reliable reproduction steps for [git-bisect].

https://www.youtube.com/watch?v=kRtQy3VrX4Y

[the triage thread]: https://forum.level1techs.com/t/looking-glass-triage/130952/2084 "Looking Glass - Triage"
[git-bisect]: https://git-scm.com/docs/git-bisect "git-bisect Documentation"

**Comment by JJRcop** [comment]
Issue seems to be resolved in 6d2c46443683c1dfe68601c80a35faf43020ff8c. Unfortunately since we don't know any reliable ways to trigger it, can't be 100% certain. If it pops up again I'll reopen this issue. If you experience this behavior in newer versions please comment here.

**Comment by ambershark-mike** [comment]
This happens to me pretty regularly using beta1.  I will check out the git commit and see if that makes it better.  

I can reproduce it pretty regularly by using full screen (-F) mode.  When using non fullscreen it's intermittent but it will happen at least a few times during a couple hours of gaming.  Usually I just pop out, kill looking glass, rerun it, and everything is good for a while from there.

I just built a new system and it happens 100% of the time in fullscreen with a RTX 2070 and an i9 9900k.  On my old system fullscreen was only intermittent.

Just wanted to add this comment in case anyone else here came looking for this like I did. :)

**Comment by gnif** [comment]
We have seen issues with some intel iGPUs when scaling up as you describe, however, it's usually lackluster performance and not randomly but constant.

Is there any chance you can film this when it occurs and post this? also check the client output to see if you have any errors/warnings popping up.

**Comment by ambershark-mike** [comment]
Yea it's definitely consistent.  I had the jittering issue that this bug was about but this scaling one is 100% of the time.  

As mentioned above I just built a new system and can't do the 2 discrete gpus due to iommu groups and motherboard space so I opted for the intel.  Works great as long as I don't scale above 1080p.

As for errors I always run the client in my terminal and I've never seen any errors.  I checked my kernel logs a few times when it happens too and didn't notice anything obvious.

https://vimeo.com/358588814
This video will show with the -a option so it's at the guest native resolution of 1080p.  Normally this plays at 60fps however it's a bit slower due to using the screen recorder at the same time.  Still playable and non-jittery.

https://vimeo.com/358589186
This video shows it scaled from 1080p to 4k.  Completely unplayable, you can see low teens in the fps in the corner and near the end you can see all the jitters.  I have had it showing 60 fps from nvidia in the corner and still had it jitter like crazy.

Also, this game will run at 60 fps (vsynced) when I change to the monitor directly.  It never dips or slows down at all.

Looking glass never had any issues when my host gpu was a 1050 gtx.  I could barely tell it wasn't native/direct.  So this is all probably the intel host gpu's fault.  I have it set to 1gb vram in my bios which is the max.  Seemed to help a small amount but didn't fix any issues.  I've played with almost every setting available in looking-glass as well with minimal results.

And finally, the only thing that pops up in kernel logs is this:

```
[35799.335831] nvidia-nvlink: Nvlink Core is being initialized, major device number 235
[35799.336340] NVRM: The NVIDIA probe routine was not called for 1 device(s).
[35799.336340] NVRM: This can occur when a driver such as: 
               NVRM: nouveau, rivafb, nvidiafb or rivatv 
               NVRM: was loaded and obtained ownership of the NVIDIA device(s).
[35799.336341] NVRM: Try unloading the conflicting kernel module (and/or
               NVRM: reconfigure your kernel without the conflicting
               NVRM: driver(s)), then try loading the NVIDIA kernel module
               NVRM: again.
[35799.336341] NVRM: No NVIDIA devices probed.
[35799.336513] nvidia-nvlink: Unregistered the Nvlink Core, major device number 235
```

That happens when I start and stop looking-glass-client.

**Comment by gnif** [comment]
It does look like it's limited by the intel GPU, please turn on the FPS in the client and see what it reports for FPS & UPS. You could also try using the legacy opengl renderer `looking-glass-client -g OpenGL` or turning off multisampling in EGL `looking-glass-client egl:multisample=no`

**Comment by ambershark-mike** [comment]
![image](https://user-images.githubusercontent.com/20294359/64570481-9d661e00-d315-11e9-9d56-f43232414a51.png)

Turning off multisample didn't help, but switching to opengl did.  It made the stuttering go away.  The UPS is still much lower than FPS as seen in the screenshot however it actually becomes playable.

Definitely not as nice as when I used the 1050 gtx as my host card but it's workable for anything short of a fast paced fps or something.

Also, thanks for your hard work on looking-glass, it's an awesome piece of work.
