### ISSUE TITLE
Suggestion: Auto enable capture mode

### ISSUE THREAD

**Issue by TerminatorNL** [gnif/LookingGlass#217]
### Required information

**Host CPU:** `AMD Ryzen 7 1800X Eight-Core Processor`
**Host GPU:** `NVIDIA Corporation GP106 [GeForce GTX 1060 6GB] [10de:1c03] (rev a1)`
**Guest GPU:** `NVIDIA Corporation GP104 [GeForce GTX 1080] [10de:1b80] (rev a1)`
Host Kernel version: `5.3.7-200.agesa_acs.fc30.x86_64` --> Fedora 30 with agesa and ACS override patch
**Host QEMU version:** `2:3.1.1-2.fc30`

### Scenario
When playing games in a virtual machine, it's quite inconvenient to "tab out" to other windows in the Linux host. Currently, this requires pressing <kbd>Scroll lock</kbd> (default) to disable capture mode and then tab to the desired application running on the host. Going back to the game you need to press <kbd>Scroll lock</kbd> again to re-enable capture mode after activating the looking glass window by clicking on it.

### Possible implementation
I am quite confident you know a lot more about this than me, feel free to correct me!

I think it should be possible to detect when the virtual machine's cursor position is changed without input from the host. If this happens, we can teleport the host machine's cursor to the appropriate location within the window-- if the looking-glass-client window is active (games like Minecraft tend to continuously teleport cursors)

For enabling this behaviour, I'd love to see a launch argument to enable it by default. If possible, a third mode to the <kbd>Scroll lock</kbd> button would be great. That would allow us to toggle between the following modes: `Capture enabled` `Capture disabled` `Capture (automatic)`. Or perhaps, <kbd>Scroll lock</kbd>+<kbd>Ctrl</kbd>?

### Thanks!
Please keep in mind that this is just a suggestion, and your product works totally fine without implementing it! I love your work and I use Looking Glass **every single day** for both productivity and gaming. Thank you very much for your hard work on this wonderful program.

**Comment by gnif** [comment]
Thank you for your well written request. We are already collecting when the cursor moves in the guest, it is required so that we can draw the cursor as it's not part of the captured image. Instead we draw the cursor on the image in the client for latency reasons. This allows us to have a UPS of say 1, but still see the cursor move around on the screen.

The issue is that you're usage is that of a full screen application that you are 'tabbing' out of, however most people using Looking Glass have a multiple monitor configuration and devote a screen to LG, exiting capture mode to move the cursor off screen to another monitor.

This automatic capture mode you describe wreak havoc with these types of setups and would be terribly confusing to those that have turned it on by accident. I am sorry but this kind of feature while would be nice for you would not suit most, and adds additional complexity to my already enormous task of maintaining this code base.

**Comment by TerminatorNL** [comment]
Understood! Thank you for the elaboration!

**Comment by troububbles** [comment]
> This automatic capture mode you describe would wreak havoc with these types of setups and would be terribly confusing to those that have turned it on by accident. I am sorry but this kind of feature while would be nice for you would not suit most, and adds additional complexity to my already enormous task of maintaining this code base.

If the user activates any undesired option by accident it is not the program's fault, that's not a good reason for not implementing it. Can you imagine how many features programs would be missing if they all applied this argument? One of the reasons we have default options and custom options is because the default options are the most recommended by the developers, but we all know some users might need different configuration. If the user changes it and finds out it wasn't what he intended he can always just disable it, but he can never blame the program just for featuring that option, that's not logical.
