### ISSUE TITLE
XBox Game Bar

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#290]
Host CPU: AMD Ryzen 5 2600
Host GPU: AMD Radeon Pro WX 2100
Guest GPU: NVIDIA GeForce GTX 1050
Host Kernel version: 5.7.7-xanmod1
Host QEMU version: 4.2.0

Unsure if this is due to the way the desktop is captured but it seems that the XBox Game Bar doesn't work over looking glass.
You can see a change of focus when opening the menus but they are just invisible.
Looking at the vm via a monitor and/or moonlight seems to show the interfaces as expected.

**Comment by anthr76** [comment]
I have noticed this as well, and been planning to try under the Nv encoder.
Likely not showing up for the same reasons you can't see UAC prompts.

**Comment by 8BallBomBom** [comment]
I have installed NvFBC but no idea how to force the host to use it.

**Comment by gnif** [comment]
You must have a professional card such as a Quadro to use NvFBC. Failure to capture the game bar is not a UAC/Secure Desktop thing, it's a failure on Microsoft's part as we are using the standard and well documented DXGI Desktop Duplication API. As such this is not a LG bug/issue and this issue is invalid.

**Comment by 8BallBomBom** [comment]
Ahhhhh didn't see that part.
Thanks.
