### ISSUE TITLE
Linux guest support

### ISSUE THREAD

**Issue by iame6162013** [gnif/LookingGlass#30]
Will linux guest support be added to this project?

**Comment by gnif** [comment]
No, Linux guest acceleration has better options available to it and unless someone want's to write the host for a Linux guest I personally will not be adding support.

**Comment by polarathene** [comment]
What are the better guest acceleration options available? Are you referring to ones that pass GL calls to the host to process? Or does accel/display work better than looking glass with some method when the guest has the GPU and renders output? VNC/Spice would have more overhead wouldn't they?

**Comment by Skeen** [comment]
I double the comment my @polarathene, what are the alternatives that are deemed to work as well as LookingGlass? - Also @gnif how much work would you say building a Linux host would be, and would you accept such work into this repository if it was committeed via a PR?

**Comment by gnif** [comment]
I have not even looked into how to capture the desktop under linux at this time, so I can not comment on the complexity. However since this project is in reality two projects in one (Windows Host and Linux Client) that require continual synchronisation as changes are made to the KVMFR protocol, etc I can not maintain a Linux Host also, the duplication of work is just a major time waste at this point in time.

Once this project reaches a stable state where things are not being tweaked continually it would be a viable option, but until then I am sorry but no, I will not accept another host application into this repository.

**Comment by polarathene** [comment]
@gnif You can capture on X11 easily enough with xshm iirc, FFMPEG and OBS are among some examples that show that. It has some differences from how DXGI works though iirc. On Wayland, I think that is now possible with PipeWire, though I don't know much about that.

You did not respond to me or Skeen about what the alternatives are that you state are better choices than LookingGlass?

@Skeen For what it's worth, I was working on a linux alternative myself. I got to the point of having both server and client running on a dual-screen host but not via guest to host. I also had the client able to support LookingGlass server from a guest to display on the host, but it wasn't 100% compatible iirc with some small differences or issues.

I haven't worked on it since due to other priorities, it's likely fallen out of sync with LookingGlass too. I might find time to work on it in future and release it with source on Github, but compatability with LookingGlass would be low priority. IIRC it could capture for X11(Linux), Windows 10(not sure about 8) and I think macOS as well, I initially wrote my own capturing code for Linux only, but later switched to a more mature library to offload the maintenance. 

SharedMemory would need support on macOS though like gnif did for getting it to work for LGs needs on Windows, not something I'm comfortable doing, I was considering a slower alternative with more overhead like UDP network packets.

**Comment by gnif** [comment]
@polarathene there are no alternatives that I am aware of, nor did I state there were any better choices. I wrote Looking Glass because there was no solution to this problem.

As for capture under Linux, at this time I really do not care to look into it. I know there are examples available and it is possible but it is not on the cards for now.

> SharedMemory would need support on macOS though like gnif did for getting it to work for LGs needs on Windows, not something I'm comfortable doing, I was considering a slower alternative with more overhead like UDP network packets.

You would need to implement a kernel driver for the ivshmem device. If you are going to use UDP perhaps you should look to alternative streaming solutions over LAN, this is not an objective of Looking Glass.

**Comment by polarathene** [comment]
>  there are no alternatives that I am aware of, nor did I state there were any better choices. 

Your 1st response on this issue to the OP is:

> No, Linux guest acceleration has better options available to it 

Perhaps there was a misunderstanding of what you mean there?

> As for capture under Linux, at this time I really do not care to look into it. I know there are examples available and it is possible but it is not on the cards for now.

That's fine, you stated you had not looked into capturing on linux so I thought I'd share my own experience/knowledge on it. As my comment later addressed, I was exploring a linux host in my own time.You've made it clear when a linux would be up for consideration for LG prior already :)

> You would need to implement a kernel driver for the ivshmem device.

Yes, not something I'm particularly confident in doing myself, hence why if I were to support macOS it'd be via alternative method, without performance as a priority.

>  If you are going to use UDP perhaps you should look to alternative streaming solutions over LAN, this is not an objective of Looking Glass.

Yes, that was the plan, to transfer frames over the virtual network. I'm aware it's not for LG, I wasn't suggesting that, sorry for going off topic a bit with my own project.

**Comment by grepwood** [comment]
Having a Linux guest would be a good thing. I prefer to play some games on Linux despite the fact they work rather crappy on my Gentoo host, so I'm left with Ubuntu VMs because porting companies don't give any attention to bug reports that mention distros other than Ubuntu.

If your only option to play Civ5 was to play it like in the screenshot below, you'd get sick and tired too.
![civ5vnc](https://user-images.githubusercontent.com/4225739/49051807-aa33de00-f1e9-11e8-8218-296bd1ee460e.png)

**Comment by gnif** [comment]
Please stop necro posting to old issues, this question has been answered and you are now just wasting my time.
