### ISSUE TITLE
Missing sources for SELinux policy module

### ISSUE THREAD

**Issue by Conan-Kudo** [gnif/LookingGlass#325]
I see 973ad5e2b054a3542ca25171b1431db6f9d4b996 added a SELinux policy binary file to the repository, but there are no sources to go with it. I expected to see `*.if`, `*.te`, and `*.fc` files that are used to create an SELinux policy module ([you can see plenty of examples here](https://github.com/fedora-selinux/selinux-policy-contrib)), but none are present. This makes it difficult to ensure that the policy module works if the underlying QEMU SELinux policy changes.

Does anyone know where this came from or if it's possible to recover the sources of the policy module to put into the codebase?

**Comment by gnif** [comment]
I do not use SELinux, and honestly SELinux + Looking Gass is a bit silly due to the fact that LG is punching a hole in VM security with the shared memory interface to begin with. As for this file, please contact the original author of the commit. If you would like to fix/correct SELinux support feel free to make a PR doing so.
