### ISSUE TITLE
Why not using the SDL_SetRelativeMouseMode mode to get relative mouse movements?

### ISSUE THREAD

**Issue by xypiie** [gnif/LookingGlass#331]
I'm a relatively new user of LookingGlass and really do like it, thanks for your great work.  Since a few weeks I'm regularly using master state db51acd to play games.

When playing shooters, I noticed, that there's some noticeable mouse stuttering when moving the mouse too fast and too wide when mousegrab is on.
I did little research in your code and saw lots of magic in the handleMouseMoveEvent() to actually get relative mouse movements for the spice_mouse_motion(rx, ry) call and I was wondering, whether it wouldn't be much easier to enable SDL_SetRelativeMouseMode when mouse grab is on.  Then you can directly use the relative mouse events event->motion.xrel / event->motion.yrel.

Please see this [patch](https://github.com/gnif/LookingGlass/files/5645585/0001-mousegrab-use-SDL-relative-mouse-movements.txt), which applies against db51acd.  It makes my gaming experience much more fluent with fast and wide mouse movements.  - Not yet perfect, but much better.

- I have seen, you changed the mouse handler since this db51acd, which unfortunately makes my personal experience even worse.

Is there a specific reason, you don't use the SDL_SetRelativeMouseMode mode when mouse grab is on?

Thanks.

**Comment by gnif** [comment]
Unfortunately, the SDL2 developers do not understand the concept of WM requests being as the term implies, a 'request' and may not be honored. As such the mouse handling code in SDL2 makes assumptions based on window position/size that break the mouse input for those using tiling window managers.

Please note though that over the last 3 days I redesigned the cursor handling code and the build you are using is missing this new functionality. You should find that all cursor-related stutters/jumps are now gone and host/client cursor sync is pretty much perfect.

**Comment by xypiie** [comment]
hm... I must disagree with you.  80d911f feels still more stuttering in mouse-grab-mode than db51acd + my patch.  Furthermore in none-mousegrab mode, it happens with 80d911f, that the mousepointer of the vm is having a hard stop within the screen and can't be moved further in one direction anymore.

To my understanding using SDL_SetRelativeMouseMode is exactly for such cases, when you don't want to have window position/size relations.  Have you talked to the SDL2 developers about what you claim they have a missing understanding?  
Cause IMHO SDL2 should be corrected if your concern is correct, as SDL2 is so widely used.  IMHO you should not have to fiddle around on your own relative mouse handler when using SDL2.

And another thing, I'm using dwm, which is a tiling window manager and can't confirm your claims about the SDL2 function breaking for me.

**Comment by gnif** [comment]
Here is the issue with the SDL2 logic, they issue a mouse cursor warp to move it back to the center of the window, as this is a queued message SDL waits for the mouse to get to that position to determine if the warp has occurred. If they were using xcb they could simply check for a cookie to determine if the cursor had done its thing, but for whatever reason, the SDL2 devs have decided to stick with the raw X11 protocol and are limited to looking for the cursor to hit the window center.

Sounds all ok, but if you dig into the SDL2 X11 implementation, you will see that the API calls that resize the window issue the X11 request to do so, and then instead of waiting on the ConfigureNotify event from X11 to verify the window dimensions changed, it immediately stores the values that were requested. These values are then used to determine the screen center and if/when the mouse warp is complete. If you are using forceAspect (which is the default) and you resize the window, SDL2 never can tell if the cursor warp is complete.

Please note that this, and other issues with SDL2 are why this mess of raw X11 event handling had to be implemented in the first place.

> that the mousepointer of the vm is having a hard stop within the screen and can't be moved further in one direction anymore.

Brand new code still being tweaked, there are several edge cases that I am yet to resolve.

**Comment by xypiie** [comment]
Thanks for this detailed information.  Good luck with your implementation.  If I'd provide you a patch to enable the SDL_SetRelativeMouseMode way via config flag to give your users (like myself) the option to chose, would you merge it?

**Comment by gnif** [comment]
Sorry no, we are not going back to the broken implementation, only PRs that fix issues with the new implementation will be accepted.
