### ISSUE TITLE
client no longer respects move window to next screen shortcut

### ISSUE THREAD

**Issue by urmamasllama** [gnif/LookingGlass#333]
In build **B2-78-g5802bfb5eb** the client no longer respects the kwin shortcut "move window to next screen" which I had been using until now to move my fullscreened LG client between my monitors. meta drag does still currently work though.

**Comment by Ghosthree3** [comment]
I assume you're talking about this https://github.com/gnif/LookingGlass/commit/4a823d0e4fdada800743a4b02f9602af95e31b38
An option was added to disable the feature, https://github.com/gnif/LookingGlass/commit/bbcaaccdcc3bd63e241fb0ba593809431c557fd0
If you launch using input:grabKeyboardOnFocus=no does it work?

**Comment by urmamasllama** [comment]
Tried that and it still didn't respect kwin shortcuts, additionally meta drag works in both cases too

**Comment by urmamasllama** [comment]
> I assume you're talking about this [4a823d0](https://github.com/gnif/LookingGlass/commit/4a823d0e4fdada800743a4b02f9602af95e31b38)
> An option was added to disable the feature, [bbcaacc](https://github.com/gnif/LookingGlass/commit/bbcaaccdcc3bd63e241fb0ba593809431c557fd0)
> If you launch using input:grabKeyboardOnFocus=no does it work?

nvm I had been calling it wrong it does fix the issue. but there is still some things to note that should be looked at. the meta key not respecting grabkeyboardonfocus is definitely an issue. additionally it seems LG or spice can't handle media key inputs
on focus
`88197625715 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 80

 88199066952 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 81

 88199091270 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 81

 88200619439 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 102

 88201363535 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 105

 88202287301 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 103

 88202335080 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 103

 88203471240 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 104

 88203975143 [W]               main.c:615  | mapScancode                    | Unable to map USB scan code: 7f
`

**Comment by gnif** [comment]
What are the "meta keys" that are failing to work?

**Comment by urmamasllama** [comment]
> What are the "meta keys" that are failing to work?

When I say meta I'm referring to the windows key. I posted this issue before I talked with you on discord yesterday

**Comment by guruthree** [comment]
I have a similar issue where with input:grabKeyboardOnFocus, the keyboard grab somehow interferes with the window manager. As a result I can't click on the title bar to move, minimize or maximize the window, or open the window icon context window. I also can't click on the window frame to resize the window. Disabling the keyboard focus (or commenting out the XGrabKeyboard) restores functionality. I don't understand why XGrabKeyboard interferes in this way, as freerdp also grabs using XGrabKeyboard and doesn't have this issue. All I can guess is that it's SDL interfering under the hood.

I've produced a workaround by calling keyboardGrab() and keyboardUngrab() in the handleWindowEnter() and handleWindowLeave() functions respectively, instead of letting the X11 focus events trigger them, see below. (Side note, it seemed like the window never unfocused when the mouse moved outside the window, so the ungrab was never called.)

https://github.com/gnif/LookingGlass/pull/340

**Comment by gnif** [comment]
This issue itself is invalid and mistitled. When keyboard input is captured/grabbed it is correct that all WM events are passed instead to the guest, and ignored by the WM. The issue here is now with relation to LG mapping scancodes correctly to the guest.

As such this issue is being closed, if there is still a problem with scancode mapping (as per the errors above) please open a new issue directly related to that problem.
