### ISSUE TITLE
[Request] Capture and stream audio back to the LookingGlass client

### ISSUE THREAD

**Issue by Vaporeon** [gnif/LookingGlass#39]
Perhaps the host application should capture audio and send that back to the client also, thus bypassing Qemu's rather lacklustre audio implementation.

One could argue that this would be a kludge and that Qemu's audio should be fixed; while true I would argue the ability to receive the audio without running it through an emulated sound device is a worthy feature in its own right.

Handling both audio and video will also come in handy for other use cases like the inevitable OBS plug-in.
My extremely quick look into audio capture on windows shows that it might involve interacting with the sound "hardware" anyway, but keep in mind that our GPU's have audio hardware too.

**Comment by zetaPRIME** [comment]
Even with the `qemu-patched` AUR package, audio from the VM is a bit glitchy. Not enough to be an issue in games, but when you're trying to use OpenMPT (because the VSTs you use really don't like Wine) it becomes a bit of an issue to hear what sounds like "buffer underruns" despite the DAW's output buffer not *actually* underrunning at any point.

**Comment by gnif** [comment]
LG is not designed to stream the audio, nor ever will be. Look to the QEMU developers to fix their audio code.

**Comment by Nexolight** [comment]
This one doesn't have noticeable latency: https://github.com/duncanthrax/scream
You may use it to get your audio.
