### ISSUE TITLE
No audio when looking glass connection is established

### ISSUE THREAD

**Issue by 0fbcb238c0** [gnif/LookingGlass#509]
I'm using Looking Glass B3 (Stable) with the 5.10.19-1 kernel under Manjaro.
VM is using Win10 20H2. Audio for the VM is HDA (ICH9).

I'm not sure if this is a bug or intended behaviour, but if the connection between client and host is established, audio output will be gone from the VM until it is shutdown and restarted. If Looking Glass is started with Spice disabled, it will work normally.

If this is intended behaviour, how should I proceed in getting audio to work with LG?
I've experimented with scream (without IVSHMEM) but couldn't get it to run. It's running on the host and in the VM, but I can't get any output.

Sorry for this "issue" but i couldn't find any info about this elsewhere. Maybe I'm just stupid.

**Comment by netboy3** [comment]
This is not a bug and is an expected behavior. Looking-Glass does not handle audio. What is happening in your case is that you get your audio to the host by using the spice viewer in virt-manager. Once LG is started, it takes over the spice connection and obviously the audio stops. Please note that you are not supposed to use a spice viewer at all with LG. You're supposed to set the display for "none", not open the console viewer at all, and drive the audio using any of numerous methods such as PulseAudio over unix socket, PulseAudio over IP, JACK or SCREAM  (not really recommended). If you are ok with using discord, we have a very active support group on the [LG Discord Server](https://discord.gg/52SMupxkvt). You're also welcome to join the LG forums at [LevelOneTechs](https://forum.level1techs.com/c/software/lookingglass/142).

**Comment by 0fbcb238c0** [comment]
Your comment about using PulseAudio sent me into the right direction.
Following the Arch wiki about setting up PA using qemu:comandline in the XML didn't work for me, as the changes would reverse when I hit 'Apply' in Virt-Manager.

I found the solution here: https://unix.stackexchange.com/questions/235414/libvirt-how-to-pass-qemu-command-line-args

`virt-xml $DOMAIN --edit --confirm --qemu-commandline '-audiodev pa,id=snd0,server=/run/user/1000/pulse/native'`
 Audio now works as expected. Thanks for your help!
