### ISSUE TITLE
[client] wayland: extra CAPS_LOCK button event sent

### ISSUE THREAD

**Issue by Leo1998** [gnif/LookingGlass#974]
I recently switched to wayland and came across this really weird bug when using vim inside the Windows VM (Caps Lock is remapped to escape). When typing certain key-combinations there is an extra CAPS_LOCK key event sent when pressing the shift key.

In the following example im pressing: a -> CAPS_LOCK -> SHIFT + a
The events in the Windows VM are:
![vm](https://user-images.githubusercontent.com/13818059/157467112-db7fad24-d3d0-43b3-b445-7a75d08b8c65.png)
The events on the linux host:
![vm2](https://user-images.githubusercontent.com/13818059/157467307-4748e750-69e7-4f12-b0b4-cb480e77826d.png)

From debugging i found out that the extra key event is produced in wayland/input.c:278 when app_handleKeyboardLEDs is called. If i remove this call the issue is fixed for me.

General questions:
- Why are we calling app_handleKeyboardLEDs when the shift key is pressed?
- Does app_handleKeyboardLEDs even do anything? When i only press CAPS_LOCK the method isn't even called. It's only invoked when pressing SHIFT for example.

I confirmed this issue is happening on bleeding edge and B5.0.1

**Comment by Xyene** [comment]
> Why are we calling app_handleKeyboardLEDs when the shift key is pressed?

It was much easier to slam the right LED state into the VM whenever it could possibly have changed, rather than try to remember what the state is within the VM (which would also be susceptible to USB-passthrough keyboards being able to change the LED state without Looking Glass knowing -- making Looking Glass query the LED state is even more complicated).

I think what's happening here is you're confusing the Windows Spice agent with your remap.

If I had to guess, without your remap, when you press <kbd>CapsLock</kbd>:

1. LG gets a `wl_keyboard.key` event and sends a <kbd>CapsLock</kbd> event to the VM. Windows turns the Caps Lock LED on.
2. LG gets a `wl_keyboard.modifier` event that says Caps Lock is on, and tells the Spice agent that the Caps Lock LED should be on.
3. The Spice agent sees the Caps Lock LED is on, and does nothing.

With your remap, when you press <kbd>CapsLock</kbd>:

1. LG gets a `wl_keyboard.key` event and sends a <kbd>CapsLock</kbd> event to the VM. This gets remapped to <kbd>Escape</kbd>. The Caps Lock LED does not turn on.
2. LG gets a `wl_keyboard.modifier` event that says Caps Lock is on, and tells the Spice agent that the Caps Lock LED should be on.
3. The Spice agent sees the Caps Lock LED is **not** on, and turns it on. Vim interprets this as <kbd>CapsLock</kbd> having been pressed.

...or some variation of the above.

> Does app_handleKeyboardLEDs even do anything? When i only press CAPS_LOCK the method isn't even called. It's only invoked when pressing SHIFT for example.

Certainly, it's called whenever we get a modifier event from the compositor. You can run `WAYLAND_DEBUG=1 looking-glass-client ... |& grep keyboard`. If you don't see a line resembling
```
[2142616.407] wl_keyboard@43.modifiers(68298, 2, 0, 2, 0)
```
when you press <kbd>CapsLock</kbd>, your compositor just isn't sending it to us (I'd be surprised if that's the case).

**Comment by Xyene** [comment]
> Another general question: Why do we even need to handle the LED states in such a complicated way on wayland?

If you toggle <kbd>CapsLock</kbd> while LG is not focused, it is reasonable to expect that when you next focus LG and start typing, you will be typing in caps. This wouldn't happen if LG wasn't handling the `wl_keyboard.modifiers` event. The same goes for <kbd>NumLock</kbd>/<kbd>ScrlLck</kbd>.

> In X11 we also don't explicitly handle this and the behaviour is perfectly fine (for me at least).

The X11 and Wayland backends are maintained by different people (@gnif for X11; @quantum and myself for Wayland), so oftentimes features will first be available in one backend before the other, but they eventually converge.

> I know this is really obscure and i might be the only one to ever come across this

I'm sympathetic to the use-case. I'm not convinced it can be made to work, but let's see what we can do.

Your first log, annotated:

```
[ 651331.688] wl_keyboard@44.key(2381, 2559116, 30, 1)          PRESS a
[ 651431.792] wl_keyboard@44.key(2382, 2559216, 30, 0)          RELEASE a
[ 651556.664] wl_keyboard@44.key(2383, 2559341, 58, 1)          PRESS CapsLock
[ 651647.692] wl_keyboard@44.key(2384, 2559432, 58, 0)          RELEASE CapsLock
[ 651766.700] wl_keyboard@44.key(2385, 2559551, 42, 1)          PRESS Shift
[ 651766.756] wl_keyboard@44.modifiers(2386, 1, 0, 0, 0)        Shift modifier on
[ 651894.739] wl_keyboard@44.key(2387, 2559679, 30, 1)          PRESS a
[ 652039.685] wl_keyboard@44.key(2388, 2559824, 42, 0)          RELEASE Shift
[ 652039.734] wl_keyboard@44.modifiers(2389, 0, 0, 0, 0)        Shift modifier off
[ 652044.707] wl_keyboard@44.key(2390, 2559829, 30, 0)          RELEASE a
```

Are you remapping <kbd>CapsLock</kbd> both in the guest _and_ the host? This log suggests you're definitely doing it in the host (since we don't see a `modifiers` event following your <kbd>CapsLock</kbd> press), but what gets sent to the VM is a <kbd>CapsLock</kbd> event, not an <kbd>Esc</kbd> (LG ignores the remap for everything but text fields in the overlay UI, because there's no arbitrary VM text injection protocol).

**Comment by Xyene** [comment]
This seems to be the culprit: https://gitlab.freedesktop.org/spice/spice/-/commit/ff9c8d4908e12db65a6cd2d61b4ed7b8174e6d78

I think this code is either broken, or doesn't support this use-case. It seems Spice speculatively assumes that a <kbd>CapsLock</kbd> key will turn on the caps modifier, and has some sort of error correction mechanism in case QEMU comes back 50ms later to tell it that it did not, in fact, turn on caps. I'm not sure what's supposed to happen to keys sent within those 50ms.

At any rate, it doesn't look like we can do anything about this in LG.

I'd suggest either:

* Remapping the key in your keyboard's firmware (if you have a keyboard that supports this).
* Running something like https://github.com/philipl/evdevremapkeys and doing the <kbd>CapsLock</kbd> &rarr; <kbd>Esc</kbd> mapping at the evdev level. This seems like the best workaround I can think of if you don't control your keyboard's firmware.
* Running a patched LG that removes the LED syncing, if the drawbacks don't bother you.

**Comment by quantum5** [comment]
Reported as https://gitlab.freedesktop.org/spice/spice/-/issues/68 to Spice.
